name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./setup.sh --with-tests
    - name: make
      run: make
    - name: test
      run: ./bin/Debug/tests
